network:
    ethernets:
        eth0:
            addresses:
            - 192.168.185.3/24
            dhcp4: true
            optional: true
        usb0:
            addresses:
            - 192.168.186.3/24
            dhcp4: false
            optional: true
    version: 2
